### ISSUE TITLE
Schema tables not displaying correctly in framework reference

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#163] opened 2018-06-26 22:55 UTC
Some schema tables are not displaying correctly in the framework reference ([example](http://standard.open-contracting.org/profiles/ppp/latest/en/framework/#i-1-1-project-name-and-description)):

![image](https://user-images.githubusercontent.com/19265814/41943686-810a261a-79f8-11e8-884c-d10bbb0484bc.png)

I think this was probably broken by a change to a community extension, I will work on resolving it.

**Comment by jpmckinney** [comment] 2018-06-26 23:47
I created an issue on the sphinxcontrib-jsonschema repo, so that we see warnings when building the documentation, so that in future we don't have to carefully test each use of the `jsonschema` directive.

**Comment by jpmckinney** [comment] 2018-06-27 00:03
Note that I've started updating standard-maintenance-scripts to work with the extracted PPP extension – so those tests will fail unless #162 is merged. If we want to push a fix for this issue without merging #162 (which still has a few steps to be completed), we can just comment out the line in .travis.yml again.

**Comment by jpmckinney** [comment] 2018-06-28 05:14
@duncandewhurst I created a PR https://github.com/OpenDataServices/sphinxcontrib-jsonschema/pull/10 which reports:

```
framework.md:65: WARNING: Include values don't exist: {'planning/project/description', 'planning/project/title'}
framework.md:85: WARNING: Include values don't exist: {'planning/project/sector'}
framework.md:105: WARNING: Include values don't exist: {'planning/project/additionalClassifications'}
framework.md:123: WARNING: Include values don't exist: {'planning/project/locations'}
framework.md:268: WARNING: Include values don't exist: {'planning/project/totalValue'}
framework.md:2860: WARNING: Include values don't exist: {'contracts/0/finance/financeType', 'contracts/0/finance/financeCategory'}
framework.md:2901: WARNING: Include values don't exist: {'contracts/0/finance/interestRate'}
framework.md:2946: WARNING: Include values don't exist: {'contracts/0/finance/stepInRights', 'contracts/0/finance/description'}
```

This should make it easier to fix the incorrect values.

**Comment by jpmckinney** [comment] 2018-06-28 05:47
The last three lines are easy to correct (add `0/` after `finance/`), but the first five lines are mysterious, as it seems they should resolve.

**Comment by duncandewhurst** [comment] 2018-06-28 23:30
Those are deep nested properties (since the definition of project was not used elsewhere we removed the ref in https://github.com/open-contracting/ocds_budget_projects_extension/pull/13 to avoid having duplicate titles and descriptions)

So perhaps sphinx is not picking those up because it expects no deep nested properties?

**Comment by jpmckinney** [comment] 2018-06-29 04:16
I had a look at the directive in https://github.com/OpenDataServices/sphinxcontrib-jsonschema but couldn't see the issue. Could you work with @Bjwebb to resolve?

**Comment by Bjwebb** [comment] 2018-07-02 16:41
Looks like the problem is that sphinxcontrib-jsonschema only picks up nested properties when `type: "object"`, whereas for `planning/project` we have `"type": ["object", "null"]`. Is that type correct? We don't have "object or null" anywhere else.

**Comment by jpmckinney** [comment] 2018-07-02 16:50
We have object and null in many places: Organization/details, Item/unit in OCDS, and others in extensions.

**Comment by Bjwebb** [comment] 2018-07-03 10:34
Ah, yes. That's what I get trying to write an update immediately before leaving.

Here's a change to sphinxcontrib-jsonschema to use all the types in a union of types - https://github.com/OpenDataServices/sphinxcontrib-jsonschema/pull/12

**Comment by jpmckinney** [comment] 2018-07-03 14:32
I'm not deeply familiar with the code, but LGTM :)

**Closed** 2018-07-04 14:41 UTC
Labels: Focus - Documentation, bug
